services:
  # ---- FastAPI backend ----
  - type: web
    name: wt-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "10000"

  # ---- Dash frontend ----
  - type: web
    name: wt-dash
    runtime: docker
    dockerfilePath: ./Dockerfile.dashboard
    plan: free
    envVars:
      - key: API_BASE
        value: "https://wt-api-hdji.onrender.com"
